baseURL = 'https://raphaelweis.com'
languageCode = 'en-us'
title = 'Raphaël Weis'
theme="hugo-md3-theme"

[params]
name = "Raphaël Weis"
email = "raphael.weis.g@gmail.com"
tagline = "French software engineering student, currently looking for an internship."
profilePicturePath = "the_solo_traveller.webp"
linkedin = "https://linkedin.com/in/raphaelweis"
github = "https://github.com/raphaelweis"

